//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoneBook
{
    using System;
    using System.Collections.Generic;
    
    public partial class PB_RECORDS
    {
        public int PBR_ID { get; set; }
        public string PBR_FAMILY_NAME { get; set; }
        public string PBR_NAME { get; set; }
        public string PBR_PHONE_NUMBER { get; set; }
    }
}
